### ISSUE TITLE
Understand result

### ISSUE THREAD

**Issue by Vonisoa** [tkmaroon/data-augmentation-for-nlp#2]
Hi, I've tried running data augmentation with french langage using bert. 
From this sentence:

`Tu es belle. Tu le sais?`

I get:

`extranjeros es belle ##. [UNK] le sais innsjøen`

Can you explain please?

**Comment by tkmaroon** [comment]
Thank you for your question!

BERT generates substitution following way.

1. The tokenizer splits an input sentence into subwords.
   e.g.) Tu es belle. Tu le sais?  -> Tu es belle ##. Tu le sais ##?
2. When you use BERT, this code generates substitution tokens with mask token prediction. Masked tokens are selected randomly.
3. Masked tokens are replaced with new tokens sampled from the output distribution of BERT.


Your Input | Tu | es | belle | ##. | Tu | le | sais | ##?
-- | -- | -- | -- | -- | -- | -- | -- | --
Mask? (randomly selected) | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 1
Masked Input for BERT | [MASK] | es | belle | ##. | [MASK] | Le | sais | [MASK]
Output | extranjeros | es | belle | ##. | [UNK] | le | sais | innsjøen
